### ISSUE TITLE
Logic issue with evaluating cased models in `run_squad.py`

### ISSUE THREAD

**Issue by qipeng** [huggingface/pytorch-transformers#1015]
## 🐛 Bug

Model I am using (Bert, XLNet....): Bert

Language I am using the model on (English, Chinese....): English

The problem arise when using:
* [x] the official example scripts: (give details) `run_squad.py` with cased models
* [ ] my own modified scripts: (give details)

The tasks I am working on is:
* [x] an official GLUE/SQUaD task: (give the name) squad
* [ ] my own task or dataset: (give details)

## To Reproduce

1. Finetune a cased model with `--do_train` and `--do_eval` (the latter is optional)
2. Use `--do_eval` to make predictions.

## Expected behavior

At evaluation time, the tokenizer should also be cased, but because it's loading from a path and not using a model name, the `from_pretrained` method in `BertTokenizer` fails to identify casing information, and the `BasicTokenizer` defaults to uncased (`do_lower_case=True`).

## Environment

(most of this is probably not relevant anyway)

* OS: Ubuntu 16.04
* Python version: 3.6.8
* PyTorch version: 1.2.0
* PyTorch Transformers version (or branch): master
* Using GPU ? Yes
* Distributed of parallel setup ? DataParallel
* Any other relevant information:

## Additional context

One solution is to add `do_lower_case=args.do_lower_case` in the kwargs here:
https://github.com/huggingface/pytorch-transformers/blob/master/examples/run_squad.py#L501

**Comment by LysandreJik** [comment]
Thanks for the bug report, will look into it.

**Comment by thomwolf** [comment]
Looks good to me, do you want to push a PR to fix this as you proposed @qipeng?

**Comment by qipeng** [comment]
Done. See #1055!

**Comment by qipeng** [comment]
Found another one: https://github.com/huggingface/pytorch-transformers/blob/master/examples/run_squad.py#L484
It seems like it should be 
```python
if args.do_train and (args.local_rank == -1 or torch.distributed.get_rank() == 0):
```
instead of
```python
if args.do_train and args.local_rank == -1 or torch.distributed.get_rank() == 0:
```
?
I.e., this block shouldn't go through unless `args.do_train` is set explicitly IMO.

**Comment by thomwolf** [comment]
Yes, good catch @qipeng and thanks for the PR, do you want to add this fix to your PR as well?

**Comment by qipeng** [comment]
Updated my PR!
