### ISSUE TITLE
fail to download vocabulary behind proxy server

### ISSUE THREAD

**Issue by jessica-lll** [huggingface/pytorch-transformers#1024]
## ❓ Questions & Help
I work behind a proxy server. Following this [issue](https://github.com/huggingface/pytorch-transformers/issues/856), I manually download the `config.json` and `pytorch_model.bin` and the model can successfully load config and model weights.

However, in running `tokenizer = BertTokenizer.from_pretrained('bert-base-cased', do_lower_case=False)`,

I get:
INFO:pytorch_transformers.file_utils:https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-cased-vocab.txt not found in cache, downloading to /tmp/tmpkat40bei
ERROR:pytorch_transformers.tokenization_utils:Couldn't reach server to download vocabulary.

If I download it manually, where should I put this vocab.txt? 
Thanks!

**Comment by andrewpatterson2018** [comment]
Put it in the same directory as your config.json file

**Comment by abhigenie92** [comment]
Which directory is it by default?

**Comment by Ashwith-mmtxt** [comment]
> Which directory is it by default?

Have you found the solution?
