### ISSUE TITLE
GPT2 Tokenizer got an expected argument `skip_special_tokens`

### ISSUE THREAD

**Issue by sashank06** [huggingface/pytorch-transformers#1032]
## ❓ Questions & Help

I keep running into this error when trying to use the GPT2 model and GPT2 tokenizer while decoding. 
Keep getting the following error when I run the piece of code below:
``tokenizer.decode(response_ids, skip_special_tokens=True)``
Error:
``TypeError: decode() got an unexpected keyword argument 'skip_special_tokens'``

**Comment by LysandreJik** [comment]
Could you please submit a bug report with the version of the library you're using?

**Comment by sashank06** [comment]
will close this issue. Opened a bug report.
