### ISSUE TITLE
GPT2 Tokenizer got an expected argument `skip_special_tokens`

### ISSUE THREAD

**Issue by sashank06** [huggingface/pytorch-transformers#1033]
## 🐛 Bug

Model I am using  -> GPT2

Language I am using the model on - >English

The problem arise when using:
I keep running into this error when trying to use the GPT2 model and GPT2 tokenizer while decoding.
Keep getting the following error when I run the piece of code below:
tokenizer.decode(response_ids, skip_special_tokens=True)
Error:
TypeError: decode() got an unexpected keyword argument 'skip_special_tokens'

* OS: Ubuntu
* Python version: 3.6.8
* PyTorch version: 1.1.0
* PyTorch Transformers version (or branch): 1.0.0
* Using GPU - Yes

**Comment by LysandreJik** [comment]
I'm having a hard time reproducing it on my side on a clean install. Could you provide a sample that throws the error?

**Comment by sashank06** [comment]
@LysandreJik I will give you the code with sample input and output asap.

**Comment by jxz2021114** [comment]
I met the same problem. Could you tell me how you solved that?
