### ISSUE TITLE
Minor bug in evaluation phase in example code for SQUAD

### ISSUE THREAD

**Issue by aakanksha19** [huggingface/pytorch-transformers#1039]
In run_squad.py, the model saving code is outside the loop which performs training (if args.do_train - line 477).
Due to this, after finetuning a model with --do_train, if we only run --do_eval, the existing trained model gets overwritten before being loaded for testing.

**Simple fix:** Pushing model saving code inside the training loop will exhibit desired behavior during testing

**Comment by Liangtaiwan** [comment]
I fixed it in #923 weeks ago.
waiting merge

**Comment by aakanksha19** [comment]
Thanks, I did not come across it earlier! I'll close this issue.
