### ISSUE TITLE
Issue in running run_glue.py in Roberta, XLNet, XLM in latest release

### ISSUE THREAD

**Issue by leslyarun** [huggingface/pytorch-transformers#1041]
## 🐛 Bug

Model I am using (Bert, XLNet....): Roberta, XLM, XLNet

Language I am using the model on (English, Chinese....): English

The problem arise when using:
* [ ] the official example scripts: run_glue.py

The tasks I am working on is:
* [ ] my own task or dataset: binary classification on my own dataset

## To Reproduce

1. Upon running glue.py with the following : python ~/pytorch-transformers/examples/run_glue.py --task_name cola --do_train  --do_eval  --do_lower_case --data_dir ~/bert-data/ --model_type roberta --model_name_or_path  roberta-base  --max_seq_length 512  --learning_rate 2e-5 --num_train_epochs 1.0   --output_dir ~/data/roberta-1/

Getting the following error:
```
08/16/2019 14:18:21 - WARNING - pytorch_transformers.tokenization_utils -   Token indices sequence length is longer than the specified maximum sequence length for this model (513 > 512). Running this sequence through the model will result in indexing errors
Traceback (most recent call last):
  File "/home/pytorch-transformers/examples/run_glue.py", line 494, in <module>
    main()
  File "/home/pytorch-transformers/examples/run_glue.py", line 447, in main
    train_dataset = load_and_cache_examples(args, args.task_name, tokenizer, evaluate=False)
  File "/home/pytorch-transformers/examples/run_glue.py", line 283, in load_and_cache_examples
    pad_token_segment_id=4 if args.model_type in ['xlnet'] else 0,
  File "/home/pytorch-transformers/examples/utils_glue.py", line 485, in convert_examples_to_features
    assert len(input_ids) == max_seq_length
AssertionError
```
2. Trying the same as above with XLNet and XLM, gives the following error:

```
08/16/2019 14:26:59 - INFO - __main__ -   Creating features from dataset file at /home/new-bert-data/keyword_data/
Traceback (most recent call last):
  File "/home/pytorch-transformers/examples/run_glue.py", line 494, in <module>
    main()
  File "/home/pytorch-transformers/examples/run_glue.py", line 447, in main
    train_dataset = load_and_cache_examples(args, args.task_name, tokenizer, evaluate=False)
  File "/home/pytorch-transformers/examples/run_glue.py", line 282, in load_and_cache_examples
    pad_token=tokenizer.encoder[tokenizer.pad_token] if args.model_type in ['roberta'] else tokenizer.vocab[tokenizer.pad_token],
AttributeError: 'XLMTokenizer' object has no attribute 'vocab'
```

## Environment

* OS: Debian
* Python version: 3.6.9
* PyTorch version: 1.2.0
* PyTorch Transformers version (or branch): 1.1.0
* Using GPU: Yes
* Distributed of parallel setup: Multi-GPU

**Comment by LysandreJik** [comment]
Thanks for the report! I'm looking into it.

**Comment by LysandreJik** [comment]
Could you try the changes in [this commit ](https://github.com/huggingface/pytorch-transformers/commit/a93966e608cac8e80b4ff355d7c61f712b6da7f4)on your own dataset and tell me if you still have errors?

**Comment by leslyarun** [comment]
@LysandreJik Ya this code works fine. Thanks for the quick fix

**Comment by LysandreJik** [comment]
Great, glad I could help!
