### ISSUE TITLE
Issue using Roberta

### ISSUE THREAD

**Issue by tuhinjubcse** [huggingface/pytorch-transformers#1047]
## 🐛 Bug

Model I am using (Bert, XLNet....): Roberta

Language I am using the model on (English, Chinese....): English

The problem arise when using:
* [x] the official example scripts: (run_glue.py)
* [ ] my own modified scripts: (give details)

![image](https://user-images.githubusercontent.com/3104771/63219474-9ac23f80-c140-11e9-98d2-efe9c8547e05.png)

The tasks I am working on is:
* [x] an official GLUE/SQUaD task: (MNLI/MRPC) 
* [ ] my own task or dataset: (give details)

## To Reproduce

just tried running run_glue.py 
see image

## Environment

* OS: Ubuntu
* Python version: 3.7.3
* PyTorch version: 1.1.0
* PyTorch Transformers version (or branch): 1.1.0
* Using GPU ? yes v100
* Distributed of parallel setup ?
* Any other relevant information:

**Comment by tuhinjubcse** [comment]
> * give details
run_glue.py

**Comment by LysandreJik** [comment]
Hello!

It seems you're having trouble accessing the file on our S3 bucket. Could it be your firewall?
If you paste the URL in your browser: https://s3.amazonaws.com/models.huggingface.co/bert/roberta-base-pytorch_model.bin

Can you download it or are you blocked?

**Comment by tuhinjubcse** [comment]
Hi 
You can close it . I managed to change firewall settings
