### ISSUE TITLE
BUG: run_openai_gpt.py bug of GPTTokenizer and GPTDoubleHeadsModel

### ISSUE THREAD

**Issue by nine09** [huggingface/pytorch-transformers#1049]
## 🐛 Bug

Model I am using (Bert, XLNet....): GPT
Language I am using the model on (English, Chinese....): ENGLISH

The problem arise when using:
* [ 1 ] the official example scripts: run_openai_gpt.py

The tasks I am working on is:
* [ 1 ] an official GLUE/SQUaD task:  ROCSroties

**Run run_openai_gpt.py file error, Traceback are as fellow:**
```
Traceback (most recent call last):
  File "/opt/lyon.li/gpt-2/examples/single_model_scripts/run_openai_gpt.py", line 288, in <module>
    main()
  File "/opt/lyon.li/gpt-2/examples/single_model_scripts/run_openai_gpt.py", line 158, in main
    model = OpenAIGPTDoubleHeadsModel.from_pretrained(args.model_name, num_special_tokens=len(special_tokens))
  File "/opt/lyon.li/gpt-2/pytorch_transformers/modeling_utils.py", line 474, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
TypeError: __init__() got an unexpected keyword argument 'num_special_tokens'
```

It seems like GPTTokenizer and GPTModel fail to add special tokens. Run fellowing demo give me result like this.
```
special_tokens = ['_start_', '_delimiter_', '_classify_']
tokenizer = OpenAIGPTTokenizer.from_pretrained(args.model_name, special_tokens=special_tokens)
special_tokens_ids = list(tokenizer.convert_tokens_to_ids(token) for token in special_tokens)
```
return
```
special_tokens_ids=[0, 0, 0]
```
That means every special tokens was mapped to unk_token when tokenize.
When init GPTModel it directly report error because `num_special_tokens`.

Anyone have some ideas about why it dose not works, thanks.

**Comment by thomwolf** [comment]
Yes, the `run_openai_gpt.py` example still needs to be updated to the new pytorch-transformers release. We haven't found time to do it yet.

**Comment by nine09** [comment]
I have pull request at #1067[https://github.com/huggingface/pytorch-transformers/pull/1067], this change fix the bug I mentioned above.
