### ISSUE TITLE
Missing tf variables in convert_pytorch_checkpoint_to_tf.py

### ISSUE THREAD

**Issue by 4everlove** [huggingface/pytorch-transformers#1072]
## 🐛 Bug

Model I am using (Bert, XLNet....): bert-base-uncased

Language I am using the model on (English, Chinese....): English

The problem arise when using:
* [x] the official example scripts: (give details)
* [ ] my own modified scripts: (give details)

The tasks I am working on is:
* [x] an official GLUE/SQUaD task: (give the name)
* [ ] my own task or dataset: (give details)

## To Reproduce

1. Fine tune BERT model using examples/run_glue.py
2. Use convert_pytorch_checkpoint_to_tf.py
3. Use run_classifier.py provided by BERT GitHub repo to do the prediction task.

Tensorflow will fail in loading the converted checkpoint, due to the missing variables 'global_step' and 'output_bias' (and maybe other variables)

**Comment by thomwolf** [comment]
Indeed.
But I don't think we will aim for two-sided compatibility with the original Bert repo anyway.
In your case, you will need to adjust the original Bert repo code to be able to load the converted pytorch model (remove the unused variables or, more simple, tweak the checkpoint loading method).

**Comment by 4everlove** [comment]
Great. Thanks for your help, @thomwolf . Closing the ticket.
