### ISSUE TITLE
How to get pooler state's (corresponds to CLS token) attention vector?

### ISSUE THREAD

**Issue by Akella17** [huggingface/pytorch-transformers#1105]
The following model definition returns the attention vector for tokens corresponding to the input sequence length, i.e. ```x.size(1)```. How do I procure the attention vector of the pooler state (output embedding corresponding to the CLS token)?

```Python
model = BertModel.from_pretrained('bert-base-uncased', output_attentions=True)
outputs = self.model(x, attention_mask = x_mask)
last_layer_attentions = outputs[2][-1] # [batch_size, num_heads, x.size(1), x.size(1)]
# I want the attention vector for pooler state, i.e. [batch_size, num_heads,  1, x.size(1)]
```

**Comment by thomwolf** [comment]
Hi, the pooler takes as input the last layer hidden-state of the first token of the sentence (the `[CLS]` token). So the attention used to compute the pooler input is just the attention for this token.

**Comment by Akella17** [comment]
@thomwolf If my understanding is right, the last layer's attention vector of the output embeddings, i.e. ```output[2][-1]```, corresponding to the input tokens **x**. I am guessing this based on the size of ```output[2][-1]```, that is ```[batch_size, num_heads, x.size(1), x.size(1)]```. So this must not include the **[CLS]** token because if it did, the size would be ```[batch_size, num_heads, (x.size(1)+1), (x.size(1)+1)]```.
