### ISSUE TITLE
sample_text.txt is broken (404 ERROR)

### ISSUE THREAD

**Issue by zbloss** [huggingface/pytorch-transformers#1106]
## ❓ Questions & Help

When I try to access the sample_text,txt file at this link, I find an nginx 404 server error.

https://huggingface.co/pytorch-transformers/samples/sample_text.txt

**Comment by thomwolf** [comment]
This one is now in the tests at: https://github.com/huggingface/pytorch-transformers/blob/master/pytorch_transformers/tests/fixtures/sample_text.txt

We'll fix the doc, thanks!
