### ISSUE TITLE
Wrong parameter name in documentation

### ISSUE THREAD

**Issue by CrafterKolyan** [huggingface/pytorch-transformers#1117]
Documentation web page: https://huggingface.co/pytorch-transformers/model_doc/gpt2.html#pytorch_transformers.GPT2DoubleHeadsModel

See `Inputs -> multiple_choice_labels`. There is actually no such parameter in `GPT2DoubleHeadsModel.forward` method. It was renamed to `mc_labels`. Also it is presented two times in documentation which seems to be just a copy past error.

Please change `multiple_choice_labels` to `mc_labels` and delete second occurrence of this parameter in documentation.

Created #1118 to fix documentation. Also you may squash it with fix of #1115

**Comment by CrafterKolyan** [comment]
Created #1118 to fix documentation. Also you may squash it with fix of #1115

**Comment by thomwolf** [comment]
Yes!
