### ISSUE TITLE
cannot import name 'RobertaConfig

### ISSUE THREAD

**Issue by wahlforss** [huggingface/pytorch-transformers#1128]
## 🐛 Bug

When I run run_glue.py with the roberta model I get an ImportError: cannot import name 'RobertaConfig'

I can't run the run_glue.py with any model since it cannot import the RobertaConfig on line 34.

Any ideas why?

**Comment by wahlforss** [comment]
Needed to update the pip package...

**Comment by stellaywu** [comment]
which pip package did you have to update? Same problem here...

**Comment by LysandreJik** [comment]
@stellaywu what is your current `transformers` or `pytorch-transformers` version?

**Comment by stellaywu** [comment]
@LysandreJik  it's transformer 2.0.0

**Comment by LysandreJik** [comment]
Thatś weird, transformers 2.0.0 works on a clean install in my environment. Could you please double check that the python code you´re running is in the same environment? Something like this:

```py
import transformers
print(transformers.__version__)
# ´2.0.0´

print(tranformers.RobertaConfig)
# Does it crash with ´AttributeError: module ´transformers´  has no attribute RobertaConfig´ ?
```

**Comment by stellaywu** [comment]
you are right, it doesn't. I have probably mixed up environment. Thanks!

**Comment by moh-yani** [comment]
> @stellaywu what is your current `transformers` or `pytorch-transformers` version?

Dear, I have an error:
`ImportError: cannot import name 'RobertaForQuestionAnswering' from 'pytorch_transformers'`

Actually, I have installed the pytorch_transformers by:
`pip install pytorch-transformers`

however, the error is occurred.

Any idea for this?

**Comment by LysandreJik** [comment]
You should upgrade your transformers version, `RobertaForQuestionAnswering` was probably not present in this early a version:

```
!pip install transformers torch
from transformers import RobertaForQuestionAnswering
```

**Comment by moh-yani** [comment]
> You should upgrade your transformers version, `RobertaForQuestionAnswering` was probably not present in this early a version:
> 
> ```
> !pip install transformers torch
> from transformers import RobertaForQuestionAnswering
> ```

Actually, I use pytorch_transformers not transformers. Could you have any suggests?

**Comment by LysandreJik** [comment]
Installing version v1.1.0 or v1.2.0 of `pytorch-transformers`, I can also import `RobertaConfig`. RoBERTa was added in v1.1.0, so any version earlier than that will not have it.

Is there a reason you're not using `transformers`? Most models are in `transformers`, as are most features, and a lot of bugs have been solved since `pytorch-transformers`.
