### ISSUE TITLE
mems output in XLNet

### ISSUE THREAD

**Issue by drasros** [huggingface/pytorch-transformers#1131]
## 🐛 Bug

Hi, 
I am trying to use memory of the last forward pass (mems arg) with XLNet. I am getting a tuple of None as mems output instead of a tuple of tensor. The same code with TransformerXL is running fine. Am I doing anything wrong or is this a bug ? Below is a short code snippet to reproduce the error. 
Many thanks,
A

```python
import torch
from pytorch_transformers import TransfoXLTokenizer, TransfoXLModel, XLNetTokenizer, XLNetModel

text = ['This is the first sentence. ', 'And this is another one']

# transformer-XL
tokenizer = TransfoXLTokenizer.from_pretrained('transfo-xl-wt103')
model = TransfoXLModel.from_pretrained('transfo-xl-wt103')
mems = None
for i in range(2):
    input_ids = torch.tensor(tokenizer.encode(text[i])).unsqueeze(0) 
    outputs = model(input_ids, mems=mems)
    mems = outputs[1]
# RUNS OK

# XLNet
tokenizer = XLNetTokenizer.from_pretrained('xlnet-large-cased')
model = XLNetModel.from_pretrained('xlnet-large-cased')
mems = None
for i in range(2):
    input_ids = torch.tensor(tokenizer.encode(text[i])).unsqueeze(0)
    outputs = model(input_ids, mems=mems)
    mems = outputs[1]
# We get tuple of None in first model output, second forward crashes.
# File "/home/asors/anaconda3/envs/psco/lib/python3.7/site-packages/pytorch_transformers/modeling_xlnet.py", line 858, in forward
#     mlen = mems[0].shape[0] if mems is not None else 0
```

Model I am using: XLNet
Language I am using the model on (English, Chinese....):

* OS: Ubuntu
* Python version: 3.7
* PyTorch version: 1.1.0
* PyTorch Transformers version (or branch): 1.1.0

**Comment by thomwolf** [comment]
Indeed I see, we have to add:
- an explanation in XLM's docstring that you should set the model configuration `mem_len` parameter if you want to use the memory (the answer to your main question). You can do for instance `model = XLNetModel.from_pretrained('xlnet-large-cased', mem_len=1024)` if you want a max memory of 1024 tokens. By default the model doesn't use memory (`mem_len = None`)
- a check in the code to avoid the error you are reporting.

**Comment by drasros** [comment]
Thanks for your reply and the new doc!

**Comment by AlaFalaki** [comment]
@thomwolf 
Hello,
I have some questions regarding how the XLnet memory and output work in this implementation.

1. As you mentioned, by default, XLnet doesn't use memory. So, how is this possible that it accepts long sequences as input (in other words, why there isn't any limit on the number of input tokens), unlike BERT, for example, that will only accept 512 sequences.

2. If I set the memory length to 512, and feed the XLnet with 512 tokens at a time (for a 1024 sequence length), also pass the memory in each step. (like the example code in the original issue) Will the final output of the network, includes all the information from the whole sequence?

To be clear, I want to use XLnet for long text summarization. So I need to feed the XLnet output to a decoder part and need a fixed-length representation.
