### ISSUE TITLE
Can't Using Binarization Script for DistilBERT

### ISSUE THREAD

**Issue by SreeramV181** [huggingface/pytorch-transformers#1140]
## 🐛 Bug

I'm currently using DistilBERT and running into issues when I run scripts/binarized_data.py. I get the following error: 

Traceback (most recent call last):
  File "scripts/binarized_data.py", line 25, in <module>
    from ..utils import logger 
ValueError: attempted relative import beyond top-level package

I haven't modified anything within the package.

**Comment by VictorSanh** [comment]
Hello @SreeramV181,
it should be fixed in commit 803c1cc4eacd38f1b854578d7d717b5e4a1ada47.
Thanks for pointing that out!
Victor
