### ISSUE TITLE
FP16_Optimizer is not an Optimizer when fp_16

### ISSUE THREAD

**Issue by anhnt170489** [huggingface/pytorch-transformers#1142]
## 🐛 Bug

When using fp_16, the scheduler should be: 

scheduler = WarmupLinearSchedule(optimizer.optimizer, warmup_steps=args.warmup_steps,
                                         t_total=num_train_optimization_steps)

if not, that will be "TypeError: FP16_Optimizer is not an Optimizer"

**Comment by thomwolf** [comment]
I think this issue should be fixed on master (even though I'm not exactly sure which script you are referring to).

**Comment by anhnt170489** [comment]
I already fixed this in my pull request. This error is caused by FP16_Optimizer, by using new Apex implementation, we deprecated FP16_Optimizer, so this bug is no longer issued

**Comment by thomwolf** [comment]
Ok closing the issue then, thanks.
