### ISSUE TITLE
Why still using old implementation of apex fp16

### ISSUE THREAD

**Issue by anhnt170489** [huggingface/pytorch-transformers#1143]
## 🚀 Feature

According to Nvidia apex fp16 documentary: https://nvidia.github.io/apex/amp.html

The implementation of new apex version doesn't require using FP16_Optimizer wrapping over FusedAdam. So I wonder why the team still kept the old implementation. Is there any special reason ? If not, I will make a pull request of implementation due to new apex version

**Comment by julien-c** [comment]
AFAIK no particular reason, feel free to open a PR
