### ISSUE TITLE
GPT2-large fails to load the tokenizer

### ISSUE THREAD

**Issue by pywirrarika** [huggingface/pytorch-transformers#1147]
## 🐛 Bug

Using: GPT2-Large

## To Reproduce
When I load the gpt2-large model, in the same way as gpt2 and gpt2-medium I get an NoneType when loading the tokenizer. 

```
self.tokenizer = GPT2Tokenizer.from_pretrained("gpt2-large", bos_token="_start_", unk_token='_unk_', eos_token="_eos_", sep_token="_delimiter_", cls_token="_classify_", pad_token='_pad_' )
self.model = GPT2LMHeadModel.from_pretrained("gpt2-large")
```
At this point in the debugger self.tokenizer == None is True
The issue is clear when I try to use the tokenizer.
```
File "gpt2_train.py", line 70, in load
    num_added_toks = self.tokenizer.add_special_tokens(special_tokens_dict)
AttributeError: 'NoneType' object has no attribute 'add_special_tokens'
```

## Expected behavior

Get a tokenizer object

## Environment

* OS: Linux
* Python version: 3.7.3
* PyTorch version: 1.1.0
* PyTorch Transformers version (or branch): 1.1.0 (last github pull)
* Using GPU ? yes
* Distributed of parallel setup ? no
* Any other relevant information:

**Comment by LysandreJik** [comment]
Hello! Could you try to install from source (1.2.0)? Is there any warning in your terminal such as 
```
Model name 'gpt2-large' was not found in model name list (gpt2, gpt2-medium). We assumed 'gpt2-large' was a path or url but couldn't...
```
or something along those lines?

**Comment by pywirrarika** [comment]
Thank you! Solved with the update. And yes, checking again I got your mentioned error message.
