### ISSUE TITLE
Closing bracket is missing in token_counts.py for DistilBERT

### ISSUE THREAD

**Issue by tomohideshibata** [huggingface/pytorch-transformers#1149]
## 🐛 Bug

Model I am using (Bert, XLNet....): DistilBERT

The problem arise when using:
* [x] the official example scripts: (give details)

I'm trying DistilBERT, and get an "invalid syntax error" when I run `examples/distillation/scripts/token_counts.py`.

A closing bracket seems missing at line 27.

```
    parser.add_argument("--data_file", type=str, default="data/dump.bert-base-uncased.pickle",
                        help="The binarized dataset."
```
 

## Environment

* OS: Linux
* Python version: 3.6.9
* PyTorch version: 1.2.0
* PyTorch Transformers version (or branch): 1.1.0
* Using GPU ? yes
* Distributed of parallel setup ? no
* Any other relevant information:

**Comment by LysandreJik** [comment]
Hi! Indeed, the closing bracket was missing, fixed it with caf1d11! Thanks for the bug report :).
