### ISSUE TITLE
ImportError: cannot import name 'DistilBertModel'

### ISSUE THREAD

**Issue by zbloss** [huggingface/pytorch-transformers#1167]
## 🐛 Bug

Can you update the pypi package? I cannot import DistilBERT on pytorch_transformers==1.1.0

**Comment by LysandreJik** [comment]
Yes, you should install it from source right now if you want to use DistilBERT. We're planning a new release 1.2.0 that includes DistilBERT + GPT-2 Large + XLM 100/17 sometimes this week :).
