### ISSUE TITLE
Write with Transformer doesn't show 774M model?

### ISSUE THREAD

**Issue by zacharymacleod** [huggingface/pytorch-transformers#1173]
According to [this twitter post](https://twitter.com/huggingface/status/1166368535221870592), Write With Transformer has been updated to include the Large model.

However, the Model & Decoder Settings only shows Small and Medium options for model size.

**Comment by zacharymacleod** [comment]
(nevermind: refreshing the page fixed it... it's weird though because I've been checking every day!)

**Comment by LysandreJik** [comment]
Hi! Your browser cache was probably playing tricks on you :)

**Comment by zacharymacleod** [comment]
That's exactly what I figured! Forgot the term for it. Kinda sucks that it did so for several days! :(

Anyways, I'm having fun with it now so it's all good!

**Comment by LysandreJik** [comment]
Glad you like it!!
