### ISSUE TITLE
XLnet output attentions doesn't work

### ISSUE THREAD

**Issue by acrola** [huggingface/pytorch-transformers#1185]
## 🐛 Bug

Model I am using - XLNet.

Language I am using the model on English.

The problem arise when using the flag `output_attentions=True`

## Expected behavior
When executing
`        outputs= self.model(input_ids) 
`
I would expect to have a tuple with outputs and attentions but it fails.
The problem probably roots from the lines:
`            if self.output_attentions:
                attentions.append(outputs[2])
`
I receive Nones instead of the attentions, or sometimes the error:
`IndexError: tuple index out of range`
For the following line in the forward function:
`attentions.append(outputs[2])`
## Environment

* OS: Windows
* Python version: 3.7.3
* PyTorch version: 1.1.0
* PyTorch Transformers version (or branch): Master branch version from 31.08.19
* Using GPU: Yes

**Comment by thomwolf** [comment]
why did you close it?

**Comment by acrola** [comment]
I'm checking, it might be my own but.

**Comment by chrisghai** [comment]
Did you figure out this one? I am having the same problem when setting `output_attentions = True` for the XLNet.
