### ISSUE TITLE
Roberta tokenizer fails on certain unicode characters

### ISSUE THREAD

**Issue by edgarxi** [huggingface/pytorch-transformers#1189]
## 🐛 Bug

Model I am using: `Roberta`:

Language I am using the model on (English, Chinese....): English

The problem arise when using:
- The `roberta-base` tokenizer and tokenizing unicode accents
```
from pytorch_transformers import *

tokenizer = RobertaTokenizer.from_pretrained('roberta-base')
phrase = "I visited the Côte d'Azur"
for word in phrase.split():
    print(tokenizer.tokenize(word))

```
this outputs: 

```
['I']
['vis', 'ited']
['the']
['C', 'Ã´', 'te']
['d', "'", 'Az', 'ur']
```

## Expected behavior
```
['I']
['vis', 'ited']
['the']
['C', 'ô', 'te']
['d', "'", 'Az', 'ur']
```
## Environment

* OS: MacOS 10.14.6
* Python version: 3.6
* PyTorch version: 1.1.0.post2
* PyTorch Transformers version (or branch): 1.1.0
* Using GPU ? no
* Distributed of parallel setup ? no
* Any other relevant information: xlnet and bert do not face this same tokenization issue. It appears that the issue comes from the gpt2-tokenizer

**Comment by julien-c** [comment]
Does `fairseq` exhibit the same behavior?

If it does, I would ask upstream. But in any case, I'm not sure it's a bug (it's just the internal encoding used by the neural net)

**Comment by ynebula** [comment]
I think you need to tokenize by XLM-Roberta-Tokenizer.
I tokenized for Korean.
