### ISSUE TITLE
Citing DistilBERT

### ISSUE THREAD

**Issue by rishibommasani** [huggingface/pytorch-transformers#1222]
Currently, my understanding is citing the repo/codebase should be done by via a link (i.e. in the paper as a footnote) as there is no citation (i.e. in BibTeX style) yet. 
For citing DistilBERT (the released model and distillation approach), how should this be done?

**Comment by VictorSanh** [comment]
Hello @rishibommasani 
Thank you for your question.
For citing DistilBERT, you're right, there is no formal write-up like an arXiv paper yet (it's definitely in our TODO stack). For the moment, I would recommend citing the blogpost as an URL.
Victor
