### ISSUE TITLE
ModuleNotFoundError in distillation/scripts/binarized_data.py

### ISSUE THREAD

**Issue by MatejUlcar** [huggingface/pytorch-transformers#1240]
Hello,

importing logger (still? I've seen previous issues, but this is the first time I'm running the code myself) throws the ModuleNotFoundError. 

```
Traceback (most recent call last):
  File "examples/distillation/scripts/binarized_data.py", line 25, in <module>
    from examples.distillation.utils import logger
ModuleNotFoundError: No module named 'examples.distillation'
```

**Comment by VictorSanh** [comment]
Hello @MatejUlcar 
Thanks for pointing that out. I fixed it once it for all by having a local logger (and not importing the global one) in commit 32e1332acf6fd1ad372b81c296d43be441d3b0b1.
