### ISSUE TITLE
pretrained model(s) in onnx format

### ISSUE THREAD

**Issue by WilliamTambellini** [huggingface/pytorch-transformers#260]
hi, would you assist/help in order to export/convert at least 1 model into the onnx format ?
https://onnx.ai
kind

**Comment by thomwolf** [comment]
Hi @WilliamTambellini, have you tried to follow the standard ONNX procedure for converting a PyTorch model?
The model in this repo are just regular PyTorch models.

**Comment by WilliamTambellini** [comment]
Hello Thomas, I ve not yet tried, just seen : 
https://stackoverflow.com/questions/54220042/how-do-you-generate-an-onnx-representation-of-a-pytorch-bert-pretrained-neural-n
Will try, tks.

**Comment by geekboood** [comment]
Hi, when I try to export a TokenClassification model to a ONNX model, I encounter `RuntimeError: ONNX export failed: Couldn't export operator aten::erf`, does that mean some part of BERT model layers not supported by ONNX?

**Comment by maeotaku** [comment]
@geekboood update your pytorch version to latest and the problem will most likely go away.

**Comment by leerumor** [comment]
for anyone who is looking for the answer:
torch=1.1.0 
python=3.6

`torch.onnx.export(model, (input_ids, segment_ids, input_mask), "bert.onnx", verbose=False)`

works well for me

**Comment by paulachocron** [comment]
> for anyone who is looking for the answer:
> torch=1.1.0
> python=3.6
> 
> `torch.onnx.export(model, (input_ids, segment_ids, input_mask), "bert.onnx", verbose=False)`
> 
> works well for me

Hi, thanks for the answer. Do you get good results when using the exported model for inference in another framework? I exported a BertForQuestionAnswering model to ONNX without errors, but I'm getting wrong predictions when using onnxruntime or a second export to TF Serving and I can't figure out why!

**Comment by chessgecko** [comment]
Not sure if this is still an issue for you but in the BertForSequenceClassification model the parameters are in a different order

`torch.onnx.export(model, (input_ids, input_mask, segment_ids), "bert.onnx", verbose=False)`

works as intended

**Comment by paulachocron** [comment]
@chessgecko wow you're right, thanks! working now

**Comment by julien-c** [comment]
cc @mfuntowicz :)
