### ISSUE TITLE
Embedding' object has no attribute 'shape' 

### ISSUE THREAD

**Issue by Dhanachandra** [huggingface/pytorch-transformers#593]
While running the script to convert the Tensorflow checkpoints to Pytorch Model. 
Model path: https://github.com/naver/biobert-pretrained/releases/download/v1.0-pubmed-pmc/biobert_pubmed_pmc.tar.gz
python pytorch_pretrained_BERT/pytorch_pretrained_bert/convert_tf_checkpoint_to_pytorch.py \
    --tf_checkpoint_path pubmed_pmc_470k/biobert_model.ckpt \
    --bert_config_file pubmed_pmc_470k/bert_config.json \
    --pytorch_dump_path pytorch_model

**Comment by DmLitov4** [comment]
Same issue with another pre-trained BERT model.
Have you managed to solve that?

**Comment by DmLitov4** [comment]
> @Dhanachandra Same issue with another pre-trained BERT model.
> Have you managed to solve that?

@Dhanachandra I've just found the solution: this exception occurs at "modeling.py" module. It's because of tensorflow->pytorch transformation. You need to find rows where 'shape' is used in modeling.py (you'll see its path in error logs) and delete it (it's somewhere in try... assert ... except..., just delete it).

**Comment by Dhanachandra** [comment]
You can use the following code: 

tf_path = 'pubmed_pmc_470k/biobert_model.ckpt'
config_path = 'pubmed_pmc_470k/bert_config.json'
pytorch_dump_path = 'pytorch_model/pytorch_model.bin'
# Save pytorch-model

import os
import re
import argparse
import tensorflow as tf
import torch
import numpy as np

from pytorch_pretrained_bert import BertConfig, BertForPreTraining

def convert_tf_checkpoint_to_pytorch(tf_checkpoint_path, bert_config_file, pytorch_dump_path):
    config_path = os.path.abspath(bert_config_file)
    tf_path = os.path.abspath(tf_checkpoint_path)
    print("Converting TensorFlow checkpoint from {} with config at {}".format(tf_path, config_path))
    # Load weights from TF model
    init_vars = tf.train.list_variables(tf_path)
    excluded = ['BERTAdam','_power','global_step']
    init_vars = list(filter(lambda x:all([True if e not in x[0] else False for e in excluded]),init_vars))
    names = []
    arrays = []
    for name, shape in init_vars:
        print("Loading TF weight {} with shape {}".format(name, shape))
        array = tf.train.load_variable(tf_path, name)
        names.append(name)
        arrays.append(array)

    # Initialise PyTorch model
    config = BertConfig.from_json_file(bert_config_file)
    print("Building PyTorch model from configuration: {}".format(str(config)))
    model = BertForPreTraining(config)

    for name, array in zip(names, arrays):
        name = name.split('/')
        # adam_v and adam_m are variables used in AdamWeightDecayOptimizer to calculated m and v
        # which are not required for using pretrained model
        if any(n in ["adam_v", "adam_m", "global_step"] for n in name):
            print("Skipping {}".format("/".join(name)))
            continue
        pointer = model
        for m_name in name:
            if re.fullmatch(r'[A-Za-z]+_\d+', m_name):
                l = re.split(r'_(\d+)', m_name)
            else:
                l = [m_name]
            if l[0] == 'kernel' or l[0] == 'gamma':
                pointer = getattr(pointer, 'weight')
            elif l[0] == 'output_bias' or l[0] == 'beta':
                pointer = getattr(pointer, 'bias')
            elif l[0] == 'output_weights':
                pointer = getattr(pointer, 'weight')
            else:
                pointer = getattr(pointer, l[0])
            if len(l) >= 2:
                num = int(l[1])
                pointer = pointer[num]
        if m_name[-11:] == '_embeddings':
            pointer = getattr(pointer, 'weight')
        elif m_name == 'kernel':
            array = np.transpose(array)
        try:
            assert pointer.shape == array.shape
        except AssertionError as e:
            e.args += (pointer.shape, array.shape)
            raise
        print("Initialize PyTorch weight {}".format(name))
        pointer.data = torch.from_numpy(array)

    # Save pytorch-model
    print("Save PyTorch model to {}".format(pytorch_dump_path))
    torch.save(model.state_dict(), pytorch_dump_path)

convert_tf_checkpoint_to_pytorch(tf_path, config_path, pytorch_dump_path) `

**Comment by Dhanachandra** [comment]
@DmLitov4

**Comment by xiaoyichao** [comment]
def load_tf_weights_in_bert(model, config, tf_checkpoint_path):
    """Load tf checkpoints in a pytorch model."""
    try:
        import re

        import numpy as np
        import tensorflow as tf
    except ImportError:
        logger.error(
            "Loading a TensorFlow model in PyTorch, requires TensorFlow to be installed. Please see "
            "https://www.tensorflow.org/install/ for installation instructions."
        )
        raise
    tf_path = os.path.abspath(tf_checkpoint_path)
    logger.info(f"Converting TensorFlow checkpoint from {tf_path}")
    # Load weights from TF model
    init_vars = tf.train.list_variables(tf_path)
    names = []
    arrays = []
    for name, shape in init_vars:
        # xyc use 自己预训练之前LayerNorm叫LayerNorm， 自己预训练，预训练叫layer_normalization这样的名字，所以需要转化
        change_name = name
        change_name_falg = False
        if name == 'bert/embeddings/layer_normalization/beta' or name == 'bert/embeddings/layer_normalization/gamma':
            change_name = name.replace('layer_normalization', 'LayerNorm')
            change_name_falg = True
        elif re.search('layer_normalization_+\d+', name):
            change_name = re.sub('layer_normalization_+\d+', 'LayerNorm', name)
            change_name_falg = True
        elif re.search('layer_normalization', name):
            change_name = re.sub('layer_normalization', 'LayerNorm', name)
            change_name_falg = True

        logger.info(f"Loading TF weight {name} with shape {shape}")
        print(f"Loading TF weight {name} with shape {shape}")
        array = tf.train.load_variable(tf_path, name)
        
        if change_name_falg:
            names.append(change_name)
        else:
            names.append(name)
        arrays.append(array)
    
    new_names = []
    for name, array in zip(names, arrays):
        name = name.split("/")
        # adam_v and adam_m are variables used in AdamWeightDecayOptimizer to calculated m and v
        # which are not required for using pretrained model
        if any(
            n in ["adam_v", "adam_m", "AdamWeightDecayOptimizer", "AdamWeightDecayOptimizer_1", "global_step"]
            for n in name
        ):
            logger.info(f"Skipping {'/'.join(name)}")
            print(f"Skipping {'/'.join(name)}")
            continue
        new_names.append(name)
        pointer = model
        for m_name in name:

                    
            if re.fullmatch(r"[A-Za-z]+_\d+", m_name):
                scope_names = re.split(r"_(\d+)", m_name)
            else:
                scope_names = [m_name]
            if scope_names[0] == "kernel" or scope_names[0] == "gamma":
                pointer = getattr(pointer, "weight")
            #  xyc use 
            # 下边这三行代码，跟这个代码的作用是一样的，这是有了_new 的后缀
            # '''
            # if m_name[-11:] == "_embeddings":
            # pointer = getattr(pointer, "weight")
            # '''
            elif scope_names[0] == 'token_type_embeddings_new':
                pointer = getattr(pointer, "token_type_embeddings")
                pointer = getattr(pointer, "weight")

            elif scope_names[0] == "output_bias" or scope_names[0] == "beta":
                pointer = getattr(pointer, "bias")
            elif scope_names[0] == "output_weights":
                pointer = getattr(pointer, "weight")
            elif scope_names[0] == "squad":
                pointer = getattr(pointer, "classifier")
            else:
                try:
                    pointer = getattr(pointer, scope_names[0])
                except AttributeError:
                    logger.info(f"except Skipping {'/'.join(name)}")
                    print(f"except Skipping {'/'.join(name)}")
                    continue
            if len(scope_names) >= 2:
                num = int(scope_names[1])
                pointer = pointer[num]
        if m_name[-11:] == "_embeddings":
            pointer = getattr(pointer, "weight")
        elif m_name == "kernel":
            array = np.transpose(array)

        try:
            if pointer.shape != array.shape:
                raise ValueError(f"Pointer shape {pointer.shape} and array shape {array.shape} mismatched")
        except AssertionError as e:
            e.args += (pointer.shape, array.shape)
            raise
        logger.info(f"Initialize PyTorch weight {name}")
        pointer.data = torch.from_numpy(array)
    return model

**Comment by xiaoyichao** [comment]
I think this function(load_tf_weights_in_bert) needs to be modified as follows:

**Comment by xiaoyichao** [comment]
I think this function(load_tf_weights_in_bert) needs to be modified as follows,'xyc use' is where I changed:
`def load_tf_weights_in_bert(model, config, tf_checkpoint_path):
    """Load tf checkpoints in a pytorch model."""
    try:
        import re

        import numpy as np
        import tensorflow as tf
    except ImportError:
        logger.error(
            "Loading a TensorFlow model in PyTorch, requires TensorFlow to be installed. Please see "
            "https://www.tensorflow.org/install/ for installation instructions."
        )
        raise
    tf_path = os.path.abspath(tf_checkpoint_path)
    logger.info(f"Converting TensorFlow checkpoint from {tf_path}")
    # Load weights from TF model
    init_vars = tf.train.list_variables(tf_path)
    names = []
    arrays = []
    for name, shape in init_vars:
        # xyc use 自己预训练之前LayerNorm叫LayerNorm， 自己预训练，预训练叫layer_normalization这样的名字，所以需要转化
        change_name = name
        change_name_falg = False
        if name == 'bert/embeddings/layer_normalization/beta' or name == 'bert/embeddings/layer_normalization/gamma':
            change_name = name.replace('layer_normalization', 'LayerNorm')
            change_name_falg = True
        elif re.search('layer_normalization_+\d+', name):
            change_name = re.sub('layer_normalization_+\d+', 'LayerNorm', name)
            change_name_falg = True
        elif re.search('layer_normalization', name):
            change_name = re.sub('layer_normalization', 'LayerNorm', name)
            change_name_falg = True

        logger.info(f"Loading TF weight {name} with shape {shape}")
        print(f"Loading TF weight {name} with shape {shape}")
        array = tf.train.load_variable(tf_path, name)
        
        if change_name_falg:
            names.append(change_name)
        else:
            names.append(name)
        arrays.append(array)
    
    new_names = []
    for name, array in zip(names, arrays):
        name = name.split("/")
        # adam_v and adam_m are variables used in AdamWeightDecayOptimizer to calculated m and v
        # which are not required for using pretrained model
        if any(
            n in ["adam_v", "adam_m", "AdamWeightDecayOptimizer", "AdamWeightDecayOptimizer_1", "global_step"]
            for n in name
        ):
            logger.info(f"Skipping {'/'.join(name)}")
            print(f"Skipping {'/'.join(name)}")
            continue
        new_names.append(name)
        pointer = model
        for m_name in name:

                    
            if re.fullmatch(r"[A-Za-z]+_\d+", m_name):
                scope_names = re.split(r"_(\d+)", m_name)
            else:
                scope_names = [m_name]
            if scope_names[0] == "kernel" or scope_names[0] == "gamma":
                pointer = getattr(pointer, "weight")
            #  xyc use 
            # 下边这三行代码，跟这个代码的作用是一样的，这是有了_new 的后缀
            # '''
            # if m_name[-11:] == "_embeddings":
            # pointer = getattr(pointer, "weight")
            # '''
            elif scope_names[0] == 'token_type_embeddings_new':
                pointer = getattr(pointer, "token_type_embeddings")
                pointer = getattr(pointer, "weight")

            elif scope_names[0] == "output_bias" or scope_names[0] == "beta":
                pointer = getattr(pointer, "bias")
            elif scope_names[0] == "output_weights":
                pointer = getattr(pointer, "weight")
            elif scope_names[0] == "squad":
                pointer = getattr(pointer, "classifier")
            else:
                try:
                    pointer = getattr(pointer, scope_names[0])
                except AttributeError:
                    logger.info(f"except Skipping {'/'.join(name)}")
                    print(f"except Skipping {'/'.join(name)}")
                    continue
            if len(scope_names) >= 2:
                num = int(scope_names[1])
                pointer = pointer[num]
        if m_name[-11:] == "_embeddings":
            pointer = getattr(pointer, "weight")
        elif m_name == "kernel":
            array = np.transpose(array)

        try:
            if pointer.shape != array.shape:
                raise ValueError(f"Pointer shape {pointer.shape} and array shape {array.shape} mismatched")
        except AssertionError as e:
            e.args += (pointer.shape, array.shape)
            raise
        logger.info(f"Initialize PyTorch weight {name}")
        pointer.data = torch.from_numpy(array)
    return model`

**Comment by xiaoyichao** [comment]
I think this function(load_tf_weights_in_bert) needs to be modified as follows,'xyc use' is where I changed:
`
def load_tf_weights_in_bert(model, config, tf_checkpoint_path):
   
    try:
        import re

        import numpy as np
        import tensorflow as tf
    except ImportError:
        logger.error(
            "Loading a TensorFlow model in PyTorch, requires TensorFlow to be installed. Please see "
            "https://www.tensorflow.org/install/ for installation instructions."
        )
        raise
    tf_path = os.path.abspath(tf_checkpoint_path)
    logger.info(f"Converting TensorFlow checkpoint from {tf_path}")
    # Load weights from TF model
    init_vars = tf.train.list_variables(tf_path)
    names = []
    arrays = []
    for name, shape in init_vars:
        # xyc use 自己预训练之前LayerNorm叫LayerNorm， 自己预训练，预训练叫layer_normalization这样的名字，所以需要转化
        change_name = name
        change_name_falg = False
        if name == 'bert/embeddings/layer_normalization/beta' or name == 'bert/embeddings/layer_normalization/gamma':
            change_name = name.replace('layer_normalization', 'LayerNorm')
            change_name_falg = True
        elif re.search('layer_normalization_+\d+', name):
            change_name = re.sub('layer_normalization_+\d+', 'LayerNorm', name)
            change_name_falg = True
        elif re.search('layer_normalization', name):
            change_name = re.sub('layer_normalization', 'LayerNorm', name)
            change_name_falg = True

        logger.info(f"Loading TF weight {name} with shape {shape}")
        print(f"Loading TF weight {name} with shape {shape}")
        array = tf.train.load_variable(tf_path, name)
        
        if change_name_falg:
            names.append(change_name)
        else:
            names.append(name)
        arrays.append(array)
    
    new_names = []
    for name, array in zip(names, arrays):
        name = name.split("/")
        # adam_v and adam_m are variables used in AdamWeightDecayOptimizer to calculated m and v
        # which are not required for using pretrained model
        if any(
            n in ["adam_v", "adam_m", "AdamWeightDecayOptimizer", "AdamWeightDecayOptimizer_1", "global_step"]
            for n in name
        ):
            logger.info(f"Skipping {'/'.join(name)}")
            print(f"Skipping {'/'.join(name)}")
            continue
        new_names.append(name)
        pointer = model
        for m_name in name:

                    
            if re.fullmatch(r"[A-Za-z]+_\d+", m_name):
                scope_names = re.split(r"_(\d+)", m_name)
            else:
                scope_names = [m_name]
            if scope_names[0] == "kernel" or scope_names[0] == "gamma":
                pointer = getattr(pointer, "weight")
            #  xyc use 
            # 下边这三行代码，跟这个代码的作用是一样的，这是有了_new 的后缀
            # '''
            # if m_name[-11:] == "_embeddings":
            # pointer = getattr(pointer, "weight")
            # '''
            elif scope_names[0] == 'token_type_embeddings_new':
                pointer = getattr(pointer, "token_type_embeddings")
                pointer = getattr(pointer, "weight")

            elif scope_names[0] == "output_bias" or scope_names[0] == "beta":
                pointer = getattr(pointer, "bias")
            elif scope_names[0] == "output_weights":
                pointer = getattr(pointer, "weight")
            elif scope_names[0] == "squad":
                pointer = getattr(pointer, "classifier")
            else:
                try:
                    pointer = getattr(pointer, scope_names[0])
                except AttributeError:
                    logger.info(f"except Skipping {'/'.join(name)}")
                    print(f"except Skipping {'/'.join(name)}")
                    continue
            if len(scope_names) >= 2:
                num = int(scope_names[1])
                pointer = pointer[num]
        if m_name[-11:] == "_embeddings":
            pointer = getattr(pointer, "weight")
        elif m_name == "kernel":
            array = np.transpose(array)

        try:
            if pointer.shape != array.shape:
                raise ValueError(f"Pointer shape {pointer.shape} and array shape {array.shape} mismatched")
        except AssertionError as e:
            e.args += (pointer.shape, array.shape)
            raise
        logger.info(f"Initialize PyTorch weight {name}")
        pointer.data = torch.from_numpy(array)
    return model

`
