### ISSUE TITLE
Using BERT as feature extractor

### ISSUE THREAD

**Issue by shivanshpatel35** [huggingface/pytorch-transformers#603]
Following file extract_features.py, I use bert-large-uncased and it outputs 4 layer outputs for each token(word). Since I want to use it as feature extractor of entire sentence, which values should I use? Or  is there any other processing we should do(like concatenate output for last token)?

**Comment by Kitiro** [comment]
i have same question

**Comment by wassname** [comment]
It's an open question on the best way to fine-tune bert and how to pool features. [This paper](https://arxiv.org/pdf/1905.05583.pdf) has a comprehensive overview. Look at table 3 specifically which found that taking the max of the last 4 layers achieves the best performance, this would be my guess. You can also look at the approaches taken by [bert-as-a-service](https://github.com/hanxiao/bert-as-service#q-what-are-the-available-pooling-strategies).
