### ISSUE TITLE
Question on duplicated sentence

### ISSUE THREAD

**Issue by youngminpark2559** [huggingface/pytorch-transformers#621]
Hi. I wonder whether they are unnecessary duplicated sentence or not.  

When I run in "test mode", similar sentences are called twice.
https://github.com/huggingface/pytorch-pretrained-BERT/blob/master/examples/run_squad.py#L908
https://github.com/huggingface/pytorch-pretrained-BERT/blob/master/examples/run_squad.py#L913

https://github.com/huggingface/pytorch-pretrained-BERT/blob/master/examples/run_squad.py#L1042
https://github.com/huggingface/pytorch-pretrained-BERT/blob/master/examples/run_squad.py#L1044

Thanks.

**Comment by MottoX** [comment]
Looks like a minor bug introduced by #248. The else statement is unnecessary.
