### ISSUE TITLE
In run_classifier.py, is "warmup_proportion" a fraction or percentage?

### ISSUE THREAD

**Issue by neurite** [huggingface/pytorch-transformers#622]
In `run_classifier.py`, the arg parameter `--warmup_proportion` [help doc](https://github.com/huggingface/pytorch-pretrained-BERT/blob/3fc63f126ddf883ba9659f13ec046c3639db7b7e/examples/run_classifier.py#L628) says, "E.g., 0.1 = 10%% of training.".  Is it actually a percentage such that `0.1` => `0.1%` => `0.001`, which is indeed `10%%` as stated in the help doc?  But throughout the code, it seems `0.1` is just fraction which is `0.1`, not `0.001`. Please clarify and fix the help doc if it is wrong.

**Comment by zycdev** [comment]
Found the same problem. `0.1` means `10%` in [Google's TensorFlow implementation](https://github.com/google-research/bert/blob/d66a146741588fb208450bde15aa7db143baaa69/run_classifier.py#L92)

**Comment by thomwolf** [comment]
It's a fraction of total training like indicated in the help doc: `0.1 = 10% of training`
