### ISSUE TITLE
Integration with a retriever Model

### ISSUE THREAD

**Issue by rajo19** [huggingface/pytorch-transformers#623]
How can I integrate BERT to a retriever model?

**Comment by thomwolf** [comment]
Have a look at the ParlAI library and in particular [these great models based on BERT](https://github.com/facebookresearch/ParlAI/pull/1331) by @samhumeau.

**Comment by tholor** [comment]
Hey @rajo19,
if you want to do Question Answering at scale with a Retriever + Reader pipeline, it might be worth checking out our new [haystack](https://github.com/deepset-ai/haystack/) project. It builds upon transformers and you can use all the QA models from [here](https://huggingface.co/models) as a reader.

**Comment by julien-c** [comment]
Very interesting, thanks for sharing @tholor! cc @mfuntowicz
