### ISSUE TITLE
BERT QnA is not matching correct answer when document is in QnA format

### ISSUE THREAD

**Issue by SandeepBhutani** [huggingface/pytorch-transformers#627]
I have BERT trained on Squad (and without trained as well) . My documents contains question and big answers. When we try to ask question as it is and BERT to find that question within document, then it gives some arbitrary answer from some other page of document. 
What can be wrong?

**Comment by mushro00om** [comment]
have you tried using your own data to train the model rather than using the squad1.1 or squad 2.0 data?
I am doing QnA system as well, I have my own data and I split them into train, dev and test data, then use the train and dev data to train the model, eventually it works ok on the test data.
because I am building the QnA system for my own task, not squad task, so I trained the model by using own data.

**Comment by SandeepBhutani** [comment]
Thanks for reply and confirming that it works. @mushro00om  May I know how much is your training data? (Building a large QnA training corpus is a challenge).

**Comment by mushro00om** [comment]
@SandeepBhutani 
My training data contain 140k questions, my dev data contain 5k questions, I haven't tried using the whole 140k to train yet because its a bit too large, I took 50k out of 140k to train, and it took roughly 3 hours.

**Comment by SandeepBhutani** [comment]
@mushro00om : Thats a huge training data set. Unfortunately creating this corpus takes a lot of effort. So we are trying to ask same question that is there as it is in the document, based on vanilla bert-uncased (or squad trained too).

**Comment by mushro00om** [comment]
@SandeepBhutani  Wish you good luck !

**Comment by dhruvkp090** [comment]
Hey @SandeepBhutani, I am facing the exact same issue. Did you solve it? I would like to talk to you about the same.

**Comment by SandeepBhutani** [comment]
Hi.. Not yet

**Comment by dhruvkp090** [comment]
@SandeepBhutani is there any way we can connect? I would like to talk to you about this..

**Comment by SandeepBhutani** [comment]
Please email me your contact details at sandtemp01@gmail.com

**Comment by dhruvkp090** [comment]
@SandeepBhutani, I sent my details.
