### ISSUE TITLE
run_classifier.py:TypeError: forward() missing 1 required positional argument: 'input_ids'

### ISSUE THREAD

**Issue by SlinZhang** [huggingface/pytorch-transformers#632]
when I use my dataset， forward() missing 1 required positional argument: 'input_ids' ,but I can get "input_ids, input_mask, segment_ids, label_ids" in batch.

**Comment by AlanHassen** [comment]
I ran into the same error and fixed it by using this instead:

[Pull Request](https://github.com/huggingface/pytorch-pretrained-BERT/pull/604)

Haven't tried my full dataset yet but on a slice, it worked well!

**Comment by Qbuer** [comment]
Same error. I solved this problem by add "CUDA_VISIBLE_DEVICES=0" in command line.
I guess this problem caused by "DataParallel" which splits batch to GPUs. In some cause, batch_size is less than the number of GPU. In consequence, model on extra gpu just get an empty input.

**Comment by rubby33** [comment]
same error when use my dataset.   File "run_classifier.py",   TypeError: forward() missing 1 required positional argument: 'input_ids'.
