### ISSUE TITLE
run_squad.py F1 and EM score are differ from tensorflow version 

### ISSUE THREAD

**Issue by rkcalnode** [huggingface/pytorch-transformers#637]
I use squad1.1 data from https://www.kaggle.com/stanfordu/stanford-question-answering-dataset

I ran convert_tf_checkpoint_to_pytorch.py (using google's uncased_L-12_H-768_A-12 model) and run_squad.py. result was
```
{"exact_match": 73.30179754020814, "f1": 82.10116863001393}
```

Alse I ran run_squad_hvd.py from https://github.com/lambdal/bert (it wraps original tensorflow BERT with horovod) and result was
```
{"exact_match": 80.66225165562913, "f1": 88.09365604437863}
```

bert_config.json is the same.

my parameter's are

pytorch ver
```
--train_batch_size", default=32,
--learning_rate", default=5e-5.
--max_seq_length", default=384,
--doc_stride", default=128,
--max_query_length", default=64
--predict_batch_size",default=8
```

tensorflow ver
```
--train_batch_size=8,
--learning_rate=5e-5,
--num_train_epochs=3.0.
--max_seq_length=384,
--doc_stride=128,
--max_query_length=64,
--predict_batch_size=8
```

I wonder
1. If src pretrained model and parameters are the same, results of pytorch version and tensorflow version are too near score, perhaps F1:88, EM:80. Is it right?
2. If 1. is true, my parameter or procedure is wrong.Where should I see?

**Comment by PeijiYang** [comment]
I also can't get the same result on my squad dataset
