### ISSUE TITLE
when I use bert-large-uncased to load bert,runtimeError occured,but base-uncase is ok

### ISSUE THREAD

**Issue by Flynn1314** [huggingface/pytorch-transformers#667]
using BertModel.from_pretrained( path of bert-large-uncased) caused error

RuntimeError: $ Torch: invalid memory size -- maybe an overflow? at ..\aten\src\TH\THGeneral.cpp:188

But using  BertModel.from_pretrained( path of bert-case-uncased)  can work

**Comment by thomwolf** [comment]
Yes, probably overflow. Try a smaller batch size?
