### ISSUE TITLE
How to use GPT2 to predict and fit a word into an existing sentence?

### ISSUE THREAD

**Issue by padmalcom** [huggingface/pytorch-transformers#686]
Hi, I'd like to know if I can use GPT2 to decorate a simple sentence such as "Peter was sad because his sister had eaten all his candy." to get sth like "Tuesday morning the ten years old Peter was sitting in his room and was sad because his mean sister Clara had eaten all his tasty candy with her friends."

Using BERT I can use BertForMaskedLM to insert [MASK] tokens into my simple sentence but results are not very good (a lot of repetitions and words do not really fit in).

Since I heard GPT2 was better for text generation I'd now like to experiment with your fantastic library but I can not really find a starting point how to insert text in an existing text instead of (what all tutorials to) add it to the end of the sentence.

**Comment by thomwolf** [comment]
You would need an insertion-based transformer model like Google's recent KERMIT (http://arxiv.org/abs/1906.01604). But unfortunately, we don't have this model in the library currently.
