### ISSUE TITLE
Include a reference on in-domain LM pre-training for BERT

### ISSUE THREAD

**Issue by lopuhin** [huggingface/pytorch-transformers#692]
From https://github.com/huggingface/pytorch-pretrained-BERT/tree/master/examples/lm_finetuning#introduction

> As such, it's hard to predict what effect this step will have on final model performance, but it's reasonable to conjecture that this approach can improve the final classification performance, especially when a large unlabelled corpus from the target domain is available, labelled data is limited, or the target domain is very unusual and different from 'normal' English text.
> If you are aware of any literature on this subject, please feel free to add it in here, or open an issue and tag me (@Rocketknight1) and I'll include it.

Hi @Rocketknight1 this paper https://arxiv.org/pdf/1905.05583.pdf studies within-task and within-domain pre-training for BERT in section 5.4 and they achieve a good boost from it.

**Comment by Rocketknight1** [comment]
Ah, thank you very much for this! I'll read over the paper and include it as a reference soon.

**Comment by Rocketknight1** [comment]
Finally read it once I had some free time at the weekend and added PR #715. Thank you!

**Comment by lopuhin** [comment]
Thank you @Rocketknight1 !
