### ISSUE TITLE
TypeError: expand_as() takes 1 positional argument but 5 were given

### ISSUE THREAD

**Issue by anxingle** [huggingface/pytorch-transformers#713]
[Model.py](https://github.com/huggingface/pytorch-pretrained-BERT/blob/master/pytorch_pretrained_bert/modeling.py) line [870](https://github.com/huggingface/pytorch-pretrained-BERT/blob/master/pytorch_pretrained_bert/modeling.py#L870):
`head_mask = head_mask.expand_as(self.config.num_hidden_layers, -1, -1, -1, -1)`   
got  the mistake,  I tried head_mask=torch.tensor([1, 2, 3]) or just like that.

**Comment by thomwolf** [comment]
Oh yes, this will be fixed in the coming PR #711.
Head mask is an option to explore the model internals, it's not for production.
See the `bertology.py` example script.
