### ISSUE TITLE
where is "pytorch_model.bin"?

### ISSUE THREAD

**Issue by jufengada** [huggingface/pytorch-transformers#739]

**Comment by amit8121** [comment]
@jufengada 

Assuming that you've installed pytorch_pretrained_bert package properly. If you load any of the `BERT` models ex: `BertForSequenceClassification` with `.from_pretrained` method with arguments for type of Bert architectures say `bert-base-uncased`; pytorch_model.bin will be downloaded from an s3 bucket to a temporary folder in your environment.

Another way is downloading entire set of pre-trained weights in to a folder from the github repository and 
 pointing the `path to pre trained weights` in the call for `.from_pretrained` method would also do the trick.
