### ISSUE TITLE
How to use Bert QA model for predictions?

### ISSUE THREAD

**Issue by Swathygsb** [huggingface/pytorch-transformers#787]
Hi,
Can you give sample codes for how to use Bert QA model for predicting an answer given a text corpus and a question?

**Comment by khaerulumam42** [comment]
You can write your own code like the prediction phase [here](https://github.com/huggingface/pytorch-pretrained-BERT/blob/78462aad6113d50063d8251e27dbaadb7f44fbf0/examples/run_squad.py#L345)

**Comment by hugoz1234** [comment]
@Swathygsb have you figured it out? I have the same use case as you and I'm struggling to understand the source code.
