### ISSUE TITLE
BertModel docstring missing pooled_output

### ISSUE THREAD

**Issue by sleepinyourhat** [huggingface/pytorch-transformers#793]
The BERT docstring describes three outputs here:

https://github.com/huggingface/pytorch-transformers/blob/master/pytorch_transformers/modeling_bert.py#L626

But none of these correspond to the pooled_output output that's added here:

https://github.com/huggingface/pytorch-transformers/blob/master/pytorch_transformers/modeling_bert.py#L713

I may be missing something, but this looks like a dated docstring.

**Comment by thomwolf** [comment]
Damned, missed that one, you are right.
Adding the missing doc-string:
```
**pooler_output**: ``torch.FloatTensor`` of shape ``(batch_size, hidden_size)``
    Last layer hidden-state of the first token of the sequence (classification token)
    further processed by a Linear layer and a Tanh activation function. The Linear
    layer weights are trained from the next sentence prediction (classification)
    objective during Bert pretraining. This output is usually *not* a good summary
    of the semantic content of the input, you're often better with averaging or pooling
    the sequence of hidden-states for the whole input sequence.
```
We'll probably do a small release in a few days once we have gathered all the feedbacks from the main release. In the meantime, I'll set up PyTorch-Hub so people can get the models from master.

**Comment by venkatasg** [comment]
A minor edit with the final two optional outputs `hidden_states` and `attentions` are tuples, not lists.

**Comment by julien-c** [comment]
cc @LysandreJik :)

**Comment by jtourille** [comment]
The documentation is outdated regarding that issue. It should probably be re-compiled :-)
