### ISSUE TITLE
[bug]BertAdam change to AdamW in example

### ISSUE THREAD

**Issue by shibing624** [huggingface/pytorch-transformers#798]
https://github.com/huggingface/pytorch-transformers/blob/master/examples/lm_finetuning/simple_lm_finetuning.py#L35  BertAdam change to AdamW

**Comment by then4p** [comment]
Changing that line still causes an error in line 568, the warmup kwarg has to be removed.

**Comment by prrao87** [comment]
#797 (specifically d6522e28732fd14a926440ef5f315e6a8e13792c)

**Comment by yzy5630** [comment]
have fix the error! I tested it on toy dataset.

**Comment by yzy5630** [comment]
@shibing624   this bug can be closed
