### ISSUE TITLE
AssertionError in BERT-Quickstart example

### ISSUE THREAD

**Issue by marcalt94** [huggingface/pytorch-transformers#803]
Hey

I tried running the Quickstart example with my own little text. Everything works fine until I get to the ```assert tokenized_text ==... ``` part. When I try to enter my text instead of the Jim Henson text, I get the following error message: ```Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AssertionError ```

I'm not sure if the error is an operation-problem or if it is an issue...

**Comment by thomwolf** [comment]
What is the full line of the assertion you are testing?
And what is your input text?

**Comment by marcalt94** [comment]
I think the mistake was with me, sorry
