### ISSUE TITLE
Where is "run_bert_classifier.py"?

### ISSUE THREAD

**Issue by amirj** [huggingface/pytorch-transformers#805]
Thanks for this great repo.
Is there any equivalent to [the previous run_bert_classifier.py](https://github.com/huggingface/pytorch-pretrained-BERT/tree/master/examples/run_bert_classifier.py)?

**Comment by thomwolf** [comment]
It's now `run_glue.py`

**Comment by bhavsarpratik** [comment]
Hi @thomwolf 
Doc needs changes from run_bert_classifier to run_glue
https://huggingface.co/pytorch-transformers/examples.html

**Comment by mtwright** [comment]
Hey, just another headsup @thomwolf 
This Doc also needs changing for the run_bert_classifier.py:
https://huggingface.co/transformers/v1.1.0/examples.html#fine-tuning-bert-examples

**Comment by julien-c** [comment]
That's an old version of the doc @mtwright (notice the `v1.1.0`), you should check out the up to date one:

https://huggingface.co/transformers/examples.html#introduction

**Comment by dhdaines** [comment]
documentation is still broken, by the way

**Comment by dhdaines** [comment]
like, here, points to a bunch of files that do not exist. also not quite sure if these instructions work anymore:

https://huggingface.co/transformers/converting_tensorflow_models.html
