### ISSUE TITLE
from pytorch-pretrained-bert to pytorch-transformers，some problem

### ISSUE THREAD

**Issue by SStarLib** [huggingface/pytorch-transformers#817]
TypeError: forward() got an unexpected keyword argument 'output_all_encoded_layers'

**Comment by thomwolf** [comment]
now you should use:
```
model = BertModel.from_pretrained('bert-base-cased', output_hidden_states=True)
outputs = model(input_ids)
all_hidden_states = outputs[-1]
```
Note that the first element in `all_hidden_states` (`all_hidden_states[0]`) is the output of the embedding layers (hence the fact that there is `num_layers + 1` elements in `all_hidden_states`).
