### ISSUE TITLE
Providing older documentation

### ISSUE THREAD

**Issue by Ricocotam** [huggingface/pytorch-transformers#826]
Hey, would it be possible to release the previous documentation ? I'm working on previous version and can't find proper doc right now. 

Thanks if you can help

**Comment by davidefiocco** [comment]
Hi, you may go to https://github.com/huggingface/pytorch-transformers/releases, select the release you are working with and in its "Assets" download the repo and navigate the code, together with documentation (?)

**Comment by thomwolf** [comment]
Hi, here is the older documentation: https://github.com/huggingface/pytorch-transformers/tree/v0.6.2
