### ISSUE TITLE
xlnet input_mask and attention_mask type error

### ISSUE THREAD

**Issue by Saner3** [huggingface/pytorch-transformers#827]
when I use:

```input_mask = (input_ids == 0)```
```perm_mask = perm_mask = torch.zeros((1, input_ids.shape[1], input_ids.shape[1]), dtype=torch.float, device=device)```
```perm_mask[:, :, -1] = 1.0  # Previous tokens don't see last token```

File "pytorch-transformers/pytorch_transformers/modeling_xlnet.py", line 881, in forward
    data_mask = input_mask[None] + perm_mask
RuntimeError: expected backend CUDA and dtype Float but got backend CUDA and dtype Byte

input_mask is a Tensor but perm_mask is FloatTensor

**Comment by thomwolf** [comment]
Humm you are right, the docstrings are off, they should both be `torch.FloatTensor`.
