### ISSUE TITLE
git pull pytorch-transformers??

### ISSUE THREAD

**Issue by Linohong** [huggingface/pytorch-transformers#834]
Hello, 
I have git cloned 'pytorch-pretrained-bert' before there is a new release, pytorch-transformers
and I added many of the comments and new example files in the cloned project. 
However, when I found there has been a new version released, git pulling didn't work 
for conflicting files issues. 
Is it because of the new release of 'pytorch-transformers' conflicts to the older version which 
is totally different in name?

**Comment by julien-c** [comment]
I suspect this is more of a general `git` question. We'll close this unless there is something specific to the lib.

Good luck!

**Comment by Linohong** [comment]
@julien-c ,
yeah, I had some of code mismatch issues and that falls into general github matters 
and I got it done :) 

Thank you  :)
