### ISSUE TITLE
AttributeError: 'BertModel' object has no attribute '_load_from_state_dict'

### ISSUE THREAD

**Issue by Shandilya21** [huggingface/pytorch-transformers#840]
Hi,
I am getting these error, even the i tried the model straight from the repository examples for the test cases.? anyone help me to understand this issues 

Thanks for help in advance

**Comment by thomwolf** [comment]
You are probably not using the new release of PyTorch-transformers.
Try `pip install pytorch-transformers --upgrade`.
And read the full [readme](https://github.com/huggingface/pytorch-transformers), there are several breaking changes.

**Comment by Shandilya21** [comment]
@thomwolf Thanks for your update, it works for me !!
