### ISSUE TITLE
Error loading converted pytorch checkpoint

### ISSUE THREAD

**Issue by hguan6** [huggingface/pytorch-transformers#853]
I am using BioBert. After converting the tensorflow checkpoint to pytorch checkpoint, I want to load it to Bert model. I found that the old pytorch-pretrained-bert works perfect but the new pytorch-transformer fails.
Here is the successful run using pytorch-pretrained-bert:

> from pytorch_pretrained_bert import BertForSequenceClassification
> model = BertForSequenceClassification.from_pretrained("biobert_v1.1_pubmed/", num_labels=1)
> exit()

Here's the failure in pytorch_transformers:

> from pytorch_transformers import BertForSequenceClassification
> model = BertForSequenceClassification.from_pretrained("biobert_v1.1_pubmed/", num_labels=1)
> 
> Model name 'biobert_v1.1_pubmed/' was not found in model name list (bert-base-uncased, bert-large-uncased, bert-base-cased, bert-large-cased, bert-base-multilingual-uncased, bert-base-multilingual-cased, bert-base-chinese, bert-base-german-cased, bert-large-uncased-whole-word-masking, bert-large-cased-whole-word-masking, bert-large-uncased-whole-word-masking-finetuned-squad, bert-large-cased-whole-word-masking-finetuned-squad, bert-base-cased-finetuned-mrpc). We assumed 'biobert_v1.1_pubmed/config.json' was a path or url but couldn't find any file associated to this path or url.
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/michael/.local/lib/python3.7/site-packages/pytorch_transformers/modeling_utils.py", line 403, in from_pretrained
>     model = cls(config)
>   File "/home/michael/.local/lib/python3.7/site-packages/pytorch_transformers/modeling_bert.py", line 958, in __init__
>     super(BertForSequenceClassification, self).__init__(config)
>   File "/home/michael/.local/lib/python3.7/site-packages/pytorch_transformers/modeling_bert.py", line 548, in __init__
>     super(BertPreTrainedModel, self).__init__(*inputs, **kwargs)
>   File "/home/michael/.local/lib/python3.7/site-packages/pytorch_transformers/modeling_utils.py", line 206, in __init__
>     self.__class__.__name__, self.__class__.__name__
> ValueError: Parameter config in `BertForSequenceClassification(config)` should be an instance of class `PretrainedConfig`. To create a model from a pretrained model use `model = BertForSequenceClassification.from_pretrained(PRETRAINED_MODEL_NAME)`

**Comment by thomwolf** [comment]
Do you have a file named `biobert_v1.1_pubmed/config.json` as mentioned in the error?

**Comment by hguan6** [comment]
Oh thanks. There is a config file name "bert_config.json" in the directory "biobert_v1.1_pubmed/". I changed the file name to "config.json" and it works! 
I am wondering why the pytorch-pretrained-bert can load the checkpoint. Maybe it reads "bert_config.json" and pytorch-transformer reads "config.json"?
