### ISSUE TITLE
CLS segment_id for BERT

### ISSUE THREAD

**Issue by guillaume-be** [huggingface/pytorch-transformers#858]
Hello,

In your example for GLUE you set the CLS segment id token to 1 for BERT: https://github.com/huggingface/pytorch-transformers/blob/2f869dc6651f9cf9253f4c5a43279027a0eccfc5/examples/run_glue.py#L259

Reading the original reference implementation it seems that CLS should have a segment_id=0. This is also aligned with several comments & docstrings you have around the code. Is this a design choice? What is the impact on general performance?

**Comment by thomwolf** [comment]
Yes, this one was also mentioned in https://github.com/huggingface/pytorch-transformers/issues/810#issuecomment-512991164.

It is fixed now.
