### ISSUE TITLE
Bug of BertTokenizer

### ISSUE THREAD

**Issue by LeeJuly30** [huggingface/pytorch-transformers#859]
when load a tokenizer from pretrain
```python
tokenizer = BertTokenizer.from_pretrained(vocab_path)
```
the vocab length is:
```python
len(tokenizer.vocab)
21128
```
but the last token of vocab is:
```python
next(reversed(tokenizer.vocab.items()))
('##😎', 21129)
```

**Comment by thomwolf** [comment]
If you are loading the chinese model, this is probably related to #860  and #825.
Should be fixed now.

**Comment by LeeJuly30** [comment]
thanks!
