### ISSUE TITLE
Deleting models

### ISSUE THREAD

**Issue by RuiPChaves** [huggingface/pytorch-transformers#861]
I would like to delete the 'bert-base-uncased' and 'bert-large-uncased' models and the tokenizer from my hardrive (working under Ubuntu 18.04). I assumed that uninstalling  pytorch-pretrained-bert would do it, but it did not. Where are these models located at?
Thanks!

**Comment by stefan-it** [comment]
Models are usually located under `~/.cache/torch/pytorch_pretrained_bert` (older version of this library) or `~/.cache/torch/pytorch_transformers` (now) :)

**Comment by RuiPChaves** [comment]
Thank you! I found it elsewhere, actually. What worked for me (quaintly) was:
 find .  -type f -size +1G -print 2>/dev/null

**Comment by raspuchin** [comment]
hey, do you guys know where it is stored on windows? thanks

**Comment by shamanez** [comment]
In my case, it gets stored  in " /tmp/torch"

**Comment by Jos1988** [comment]
In my case I found a variable containing the default cache path.
Run the following in python:
```
from transformers import file_utils
print(file_utils.default_cache_path)
```

If it is not there, check your environmental variables.

In my current transformers version `PYTORCH_PRETRAINED_BERT_CACHE`, `PYTORCH_TRANSFORMERS_CACHE` and `TRANSFORMERS_CACHE` can overwrite the default cache path.
