### ISSUE TITLE
PreTrainedModel.from_pretrained(...) doesn't pass cache_dir to PretrainedConfig.from_pretrained(...)

### ISSUE THREAD

**Issue by mbugert** [huggingface/pytorch-transformers#863]
The cache_dir key-value parameter does not work as intended in `PreTrainedModel.from_pretrained(...)`. It is popped from the kwargs, then `PretrainedConfig.from_pretrained(...)` is called which expects this parameter in the kwargs, but it's obviously not there anymore. A default location is used as a fallback, but this leads to strange behaviour if this default location doesn't exist or isn't writable (as it was in my case).

**Comment by thomwolf** [comment]
Fix with #866
