### ISSUE TITLE
Can lm_finetuning be used with non-english data ? 

### ISSUE THREAD

**Issue by ereday** [huggingface/pytorch-transformers#885]
Hi, 
My target domain is in German. Can I still use the scripts &codes under `lm_finetuning` folder to finetune pre-trained Bert models  or are those only for English target domains?

**Comment by stefan-it** [comment]
@ereday Take the `simple_lm_finetuning.py`script for example. It has a `--bert_model` argument. When your target domain is German, then you should use the recently introduced [BERT model for german](https://github.com/huggingface/pytorch-transformers/pull/688) via passing `bert-base-german-cased`. 

This should fine-tune the German BERT model :)

**Comment by ereday** [comment]
@stefan-it  thanks alot. I wasn't aware of german specific bert model. Awesome!
