### ISSUE TITLE
Increased number of hidden states returned from transformers in latest release

### ISSUE THREAD

**Issue by xanlsh** [huggingface/pytorch-transformers#889]
I noticed an (undocumented?) change in the latest release: namely that transformers now include the pre-encoder input vector in the list returned when `output_hidden_states` is True.

For example, the `hidden_states` output from `BertEncoder` now returns a length-13 list of tensors, whereas it used to return a length-12 list for each of Bert's 12 encoder modules

The change does seem to be intentional, as we have the following line in the tests

https://github.com/huggingface/pytorch-transformers/blob/067923d3267325f525f4e46f357360c191ba562e/pytorch_transformers/tests/modeling_common_test.py#L244

Personally I'm not affected, I just wanted to double-check that this was intended behavior

**Comment by rishibommasani** [comment]
Yes, this is the initial embedding layer (i.e. this is layers "0" through 12 or 24). There are a number of small changes that haven't been migrated into the documentation yet.
