### ISSUE TITLE
BERT: run_squad.py falling over after eval

### ISSUE THREAD

**Issue by jforbes14** [huggingface/pytorch-transformers#891]
I'm having an issue fine-tuning BERT with run.squad.py, as it falls over at the end of the evaluation stage. I'm fine tuning on SQuAD v1.1. Has anyone else encountered the same issue, or is able to point out where I'm going wrong?

`python run_squad.py \
    --model_type bert \
    --model_name_or_path bert-base-uncased \
    --do_train \
    --do_eval \
    --do_lower_case \
    --overwrite_output_dir \
    --train_file $TRAIN_FILE \
    --predict_file $PREDICT_FILE \
    --learning_rate 2e-5 \
    --num_train_epochs 1.0 \
    --max_seq_length 384 \
    --per_gpu_eval_batch_size=12   \
    --per_gpu_train_batch_size=12   \
    --output_dir /content/SQuAD_for_bert/models/bert_base_uncased_finetuned_script/`

Which completes fine-tuning the model, and then fits the eval set but returns:

`Evaluating: 100% 257/257 [01:29<00:00,  2.86it/s]
07/22/2019 02:17:18 - INFO - utils_squad -   Writing predictions to: /content/SQuAD_for_bert/models/bert_base_uncased_finetuned_script/predictions_.json
07/22/2019 02:17:18 - INFO - utils_squad -   Writing nbest to: /content/SQuAD_for_bert/models/bert_base_uncased_finetuned_script/nbest_predictions_.json
Traceback (most recent call last):
  File "run_squad.py", line 521, in <module>
    main()
  File "run_squad.py", line 510, in main
    result = evaluate(args, model, tokenizer, prefix=global_step)
  File "run_squad.py", line 257, in evaluate
    results = evaluate_on_squad(evaluate_options)
  File "/content/SQuAD_for_bert/utils_squad_evaluate.py", line 291, in main
    with open(OPTS.na_prob_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/content/SQuAD_for_bert/models/bert_base_uncased_finetuned_script/null_odds_.json'`

(Running this in Google Colab - in case that is of any relevance).

Any help would be greatly appreciated - thanks!

**Comment by thomwolf** [comment]
Fixed in #882
