### ISSUE TITLE
Export to Tensorflow not properly implemented

### ISSUE THREAD

**Issue by dhpollack** [huggingface/pytorch-transformers#918]
Apologies for going about this backwards.  I created a pull request #907 to fix your implementation of converting pytorch weights to tensorflow weights.  As explained in the PR, the current implementation puts the weights from the pytorch model into two places in the newly created tensorflow checkpoint.  The fix not only reduces the size of the meta file, but also reduces the running time.

**Comment by thomwolf** [comment]
Thanks @dhpollack !
