### ISSUE TITLE
Code snippet on docs page using old import

### ISSUE THREAD

**Issue by andrewnc** [huggingface/pytorch-transformers#919]
This is a documentation issue. I couldn't find where to edit the website source https://huggingface.co/pytorch-transformers/torchscript.html

On that page the code snippet still uses `from pytorch_pretrained_bert import BertModel, BertTokenizer, BertConfig`

The documentation in this repo under [https://github.com/huggingface/pytorch-transformers/blob/master/docs/source/torchscript.rst](url) is correct. 

This seems like a simple sync error

**Comment by thomwolf** [comment]
Thanks!
