### ISSUE TITLE
CONFIG_NAME and WEIGHTS_NAME are missing in modeling_transfo_xl.py

### ISSUE THREAD

**Issue by tomohideshibata** [huggingface/pytorch-transformers#950]
When I run `convert_transfo_xl_checkpoint_to_pytorch.py`, the following error occurs.
```
Traceback (most recent call last):
  File "convert_transfo_xl_checkpoint_to_pytorch.py", line 27, in <module>
    from pytorch_transformers.modeling_transfo_xl import (CONFIG_NAME,
ImportError: cannot import name 'CONFIG_NAME'
```

So, in `modeling_transfo_xl.py`, `from .modeling_utils import (PretrainedConfig, PreTrainedModel, add_start_docstrings)` should be `from .modeling_utils import (CONFIG_NAME, WEIGHTS_NAME, PretrainedConfig, PreTrainedModel, add_start_docstrings)`.

**Comment by thomwolf** [comment]
Thanks!
