### ISSUE TITLE
How to output a vector

### ISSUE THREAD

**Issue by Wenenen** [huggingface/pytorch-transformers#965]
How to use BertModel to output a word's vector which like a vector in word2vec?

**Comment by LysandreJik** [comment]
Hi, you can use the BertModel to give you the encoded representation of the word ids you have as input. The tensor output by the model’s last layer (of dimension `(batch_size, sequence_length, 768)` for the BertModel) can be considered as the BERT-encoded representation of your input and then be used as input for a downstream task. Is this what you were looking for?

**Comment by Wenenen** [comment]
i want to get the word embedding

**Comment by Wenenen** [comment]
I want to get the word embedding.
Is the following code correct?
    model = BertModel.from_pretrained('ms')
    embedding = model.embeddings.word_embeddings
‘ms’ is my pretrained bert model path

**Comment by LysandreJik** [comment]
Yes, that works!

**Comment by Wenenen** [comment]
thanks!
