### ISSUE TITLE
Finetune GPT2 

### ISSUE THREAD

**Issue by rabeehk** [huggingface/pytorch-transformers#969]
Hi
According to pytorch-transformers/docs/source/index.rst
There was a run_gpt2.py example which also shows how to finetune GPT2 on the training data.
I was wondernig if you could add this example back, and proving sample script to finetune GPT2.
thanks.
Best regards,
Rabeeh

**Comment by LysandreJik** [comment]
Hi Rabeeh,

We are currently working on an updated example on fine-tuning generative models, especially GPT-2. The example should be up later this week, keep an eye out!

**Comment by letsgoduke** [comment]
Any update on when this example will be available?  Thanks!

**Comment by aiscientist** [comment]
Hope this issue won't be closed until the example is done.

**Comment by LysandreJik** [comment]
The script is being worked on over at https://github.com/huggingface/pytorch-transformers/pull/987. It works for GPT/GPT-2 but it isn't ready for BERT/RoBERTa so we're not releasing it yet.

It shows how to fine-tune GPT-2 using causal language modeling on WikiText-2.

**Comment by ruidongtd** [comment]
Any update on when this example will be available? Thanks!
The link of "see relevant file here" is 404

**Comment by thomwolf** [comment]
Oh yes, the script is out.

It was renamed `run_lm_fintuning.py` you can find it in the `examples` folder: https://github.com/huggingface/pytorch-transformers/blob/master/examples/run_lm_finetuning.py

**Comment by Henry-E** [comment]
Silly question but how do you know which gpt-2 model is being trained? Does it default to the largest one available. I could find any indication of which size model is being used in the fine tuning script.

**Comment by thomwolf** [comment]
Hi Henry,
Default to the small one.
You can select the size with the `model_name_or_path` argument. Just put in
the argument the relevant shortcut name for the model as listed [here](
https://huggingface.co/transformers/pretrained_models.html).

**Comment by Henry-E** [comment]
Ah got it, thanks!

**Comment by texturejc** [comment]
` run_lm_fintuning.py` is no longer available in the examples folder when you clone the transformers repo. Is there a reason for this? It was available a couple of months ago.

**Comment by julien-c** [comment]
It’s named run_language_modeling.py now

**Comment by texturejc** [comment]
Great, thanks!

**Comment by iliemihai** [comment]
This may sound silly also, but will `run_lm_fintuning.py` be able to finetune microsoft/DialoGPT model on a custom dataset?  Thank you

**Comment by LysandreJik** [comment]
Yes, but it's named `run_language_modeling.py` now.
