### ISSUE TITLE
Brackets are not aligned in the DocString of Bert.

### ISSUE THREAD

**Issue by jiaxin96** [huggingface/pytorch-transformers#971]
The Brackets in the file https://github.com/huggingface/pytorch-transformers/blob/master/pytorch_transformers/modeling_bert.py#L606 are not aligned, which will cause some highlight mistakes in some editers (i.e. VSCODE).
it should be fixed as : [0, config.max_position_embeddings - 1]

**Comment by thomwolf** [comment]
You're right, will fix! cc @LysandreJik
