### ISSUE TITLE
Pretrained GPT2 mdoels does not load unk special symbol

### ISSUE THREAD

**Issue by pywirrarika** [huggingface/pytorch-transformers#994]
## 🐛 Bug

Im using GPT2 (on pytorch-transformers 1.0.0) using the introductory tutorial but it seems that the tokenizer does not load the unk special symbol from the pretrained dictionary.

`
tokenizer = GPT2Tokenizer.from_pretrained('gpt2')
model = GPT2Model.from_pretrained('gpt2')
print(tokenizer.unk_token)

`
The output from the above code is as follows:

`Using unk_token, but it is not set yet.
None`

Is this the expected behavior? 

Thank you!

## Environment

* OS: Linux
* Python version: 3.7.3
* PyTorch version:1.1.0
* PyTorch Transformers version (or branch):1.0.0
* Using GPU ? yes
* Distributed of parallel setup ? no
* Any other relevant information: -

**Comment by LysandreJik** [comment]
Hi! GPT-2 does not have an unknown token because of its byte-level BPE. This is a warning so it should not affect your code, but maybe we should do something about this warning for models that do not have unknown tokens. cc @thomwolf.

**Comment by pywirrarika** [comment]
However, it seems that having a defined _unk_ symbol is necessary to run other methods, like 
`def add_tokens(self, new_tokens)`
If the unk_token is set to None, add_special_tokens() breaks calling add_tokens() because the None type that is returned from convert_tokens_to_ids.

**Comment by thomwolf** [comment]
Yes, it's already on master if you compile from source and will be in the next (1.1) release (which will likely be released next week).

**Comment by pywirrarika** [comment]
Thank you very much!
