### ISSUE TITLE
Is XLA feature existed in current repo?

### ISSUE THREAD

**Issue by geekan** [huggingface/pytorch-transformers#997]
## ❓ Questions & Help

I find https://news.developer.nvidia.com/nvidia-achieves-4x-speedup-on-bert-neural-network/ says tensorflow XLA has higher speed on bert, however, the pull request in this repo it mentioned https://github.com/huggingface/pytorch-pretrained-BERT/pull/116 didn't implement something like XLA. Is the XLA feature already exist?

**Comment by LysandreJik** [comment]
Hi, there is no XLA/TPU support with the current library. Maybe in a future release!
